name: Test workflow
run-name: Test workflow ${{ github.run_number }}

defaults:
  run:
    shell: bash

on: [workflow_dispatch] # this is a comment

permissions:
  contents: read


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
          echo "yay"
